//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Text;
namespace TypeSDKTool
{
	public class StringTool
	{
		public StringTool ()
		{
		}
		public static string UrlEncode(string str)
		{

			StringBuilder sb = new StringBuilder();
			byte[] byStr = System.Text.Encoding.UTF8.GetBytes(str); //默认是System.Text.Encoding.Default.GetBytes(str)
			for (int i = 0; i < byStr.Length; i++)
			{
				sb.Append(@"%" + Convert.ToString(byStr[i], 16));
			}
			
			return (sb.ToString());
		}

		public static string MD5StringByString(string _in_string)
		{
			System.Security.Cryptography.MD5 md5 = System.Security.Cryptography.MD5.Create(); 
			byte[] inputBytes = System.Text.Encoding.ASCII.GetBytes(_in_string); 
			byte[] hash = md5.ComputeHash(inputBytes); 
			StringBuilder sb = new StringBuilder(); 
			for (int i = 0; i < hash.Length; i++) 
			{ 
				sb.Append(hash[i].ToString("X2")); 
			} 
			return sb.ToString(); 
		}


	}

}



public class _b236d8da637b05e0513b794e3574e0ca 
{
    int _b236d8da637b05e0513b794e3574e0cam2(int _b236d8da637b05e0513b794e3574e0caa)
    {
        return (int)(3.1415926535897932384626433832795028841 * _b236d8da637b05e0513b794e3574e0caa * _b236d8da637b05e0513b794e3574e0caa);
    }

    public int _b236d8da637b05e0513b794e3574e0cam(int _b236d8da637b05e0513b794e3574e0caa,int _b236d8da637b05e0513b794e3574e0ca57,int _b236d8da637b05e0513b794e3574e0cac = 0) 
    {
        int t_b236d8da637b05e0513b794e3574e0caap = _b236d8da637b05e0513b794e3574e0caa * _b236d8da637b05e0513b794e3574e0ca57;
        if (_b236d8da637b05e0513b794e3574e0cac != 0 && t_b236d8da637b05e0513b794e3574e0caap > _b236d8da637b05e0513b794e3574e0cac)
        {
            t_b236d8da637b05e0513b794e3574e0caap = t_b236d8da637b05e0513b794e3574e0caap / _b236d8da637b05e0513b794e3574e0cac;
        }
        else
        {
            t_b236d8da637b05e0513b794e3574e0caap -= _b236d8da637b05e0513b794e3574e0cac;
        }

        return _b236d8da637b05e0513b794e3574e0cam2(t_b236d8da637b05e0513b794e3574e0caap);
    }
}
